### ISSUE TITLE
How does your logic-input work?

### ISSUE THREAD

**Issue by amcsi** [laszlokorte/tams-tools#1]
Hey I would really like to know how your textarea works that can show fancy stuff along with normal text.

https://github.com/laszlokorte/tams-tools/blob/master/app/components/logic/input-field/view/index.js#L66-L78

When observing it with Chrome Developer Tools, I saw that there's no "contenteditable" attribute set on the overlay div. I also couldn't seem to find any logic in your JavaScript code that seemed to make that editable overlay thing work.

How does it work? It looks slick and I want one like that for one of my projects!

**Comment by laszlokorte** [comment]
Hi @amcsi,
I am not using a `contenteditable` because I do not want to take care of all the formatting issues.

The trick is the `.logic-input-overlay` div in the range you already linked: https://github.com/laszlokorte/tams-tools/blob/master/app/components/logic/input-field/view/index.js#L75-L77

together with these style definitions:
https://github.com/laszlokorte/tams-tools/blob/master/app/components/logic/input-field/view/index.styl#L21-L72

`.logic-input-field` is the textarea
`.logic-input-overlay` is a div that has the exact same style definitions as the text area (`word-wrap`, `white-space`...)
Both are positioned absolute inside a common parent container.

The overlay div has a greater `z-index` so it overlays the `textarea`.

Now via javascript I just duplicate the `textarea`'s  content into the overlay div and wrap the error tokens inside a span.

If there are multiple line breaks in the value (manual or forced via word-wrap) the text-area gets resized via javascript to match the text height. The overlay automatically adjusts to it's content text size.
The container has set a `max-height` and `overflow: scroll` so when there are more then 7 lines the container will be scrollable so it scrolls both the overlay and the textarea. The textarea itself is not scrollable.

**Comment by amcsi** [comment]
Oh wow I haven't heard of `pointer-events: none`, that's great!

When I was observing the textarea with Chrome Developer Tools, it was always empty even when I entered text. That confused me to a large extent and made me think in the wrong direction. Now that I look at it again, when I ask for the textarea's value with JavaScript, it does have the value of characters in it; it just seems like Chrome does not update it in the textarea element in Developer Tools.

Anyway, many thanks and very cool project! :)
